### PR TITLE
Casting away constness fixed

### PR DESCRIPTION
**Pull request by mpusz**

### CODE REVIEW

**Comment by potswa** [comment]
Hi Mateus,

It’s not completely clear what this fixes. Can you please add a testcase?

Best,
David

**Comment by mpusz** [comment]
Well, I cannot provide a testcase as this is a compilation issue. It does not compile for me on gcc9 with restrictive compiler flags:

```
[build] ../../external/cxx_function/include/cxx_function.hpp:324:20: error: cast from type ‘const cxx_function::impl::erasure_base*’ to type ‘cxx_function::impl::local_erasure<{anonymous}::pcap::http_listener::start()::<lambda(const error_code&, net_pcap::ip::tcp::socket&&)> >*’ casts away qualifiers [-Werror=cast-qual]
[build]   324 |         { return ( (typename transfer_sig_qualifiers< sig, local_erasure>::type) self ).target( std::forward< arg >( a ) ... ); }
[build]       |                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by potswa** [comment]
This one is failing `badcopy.cpp` and `constructible.cpp` testcases.

**Comment by potswa** [comment]
This was the intent of using a C cast there. Likely the proper fix is to locally disable the warning with a pragma.

**Comment by mpusz** [comment]
Or use a `const_cast` if that was your intention ;-)

**Comment by potswa** [comment]
Hi @mpusz, on reviewing my code, I think this was a nice warning because none of those `const` should even exist. I have tried putting the `const_cast` closer to the library interface and changing the C cast to `static_cast`. Can you please test using the branch, `non-const-call-internals`, which is linked above?

**Comment by potswa** [comment]
Added `-Wcast-qual` to my GCC/Clang test script and merged `non-const-call-internals`.

**Pull request closed without merging**
